### ISSUE TITLE
Afvalwijzer blueprint not loading

### ISSUE THREAD

**Issue by bobvmierlo** [dwainscheeren/dwains-dashboard-blueprints#45]
After installing all prerequisites the afvalwijzer blueprint is not loading when pasted in the YAML field.
I've installed 5 other blueprint pages without any issues.

**Comment by bobvmierlo** [comment]
Just noticed a typo in the blueprint.
```
blueprint:
  name: Afvalwijzer page Blueprint
  description: An afvalwijzer blueprint page by Jeroen Klompen
  version: "1.0"
  type: card
```

I changed the 'type' to page and then it worked.
